name: Python application test with Github Actions

on:
  push:
    branches:
    - main
  pull_request:

jobs:
     
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        make install
    - name: Lint with pylint
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
    - name: Trigger CD on azure devops
    - uses: Azure/pipelines@v1
      with:
        azure-devops-project-url: 'https://dev.azure.com/ronnaldmachado0697/Agile_ML_Engineer'
        azure-pipeline-name: 'rrm86.Agile_ML_Engineer' # name of the Azure pipeline to be triggered
        azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
